services:
  - type: web
    name: aternos-bot
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 8932716211:AAEC1-wnXkYWP2n4d2RtdaynBKkEq0H0JNs
      - key: ATERNOS_USER
        value: GodB1T
      - key: ATERNOS_PASS
        value: AntonGod
      - key: SERVER_ID
        value: ZMbbJv4TMQFIbi78
      - key: LOG_CHAT_ID
        value: "-1002221201789"
      - key: PORT
        value: "5000"
